[versions]
agp = "8.4.0"
fragment = "1.7.0"
generativeai = "0.5.0"
guava = "32.0.1-android"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
firebase-firestore = "25.0.0"
firebase-auth = "23.0.0"
picasso = "2.71828"
reactiveStreams = "1.0.4"
firebaseStorage = "21.0.0"

[libraries]
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebase-firestore" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebase-auth" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
reactive-streams = { module = "org.reactivestreams:reactive-streams", version.ref = "reactiveStreams" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

